### ISSUE TITLE
Cannot add foreign key constraint 

### ISSUE THREAD

**Issue by nachete1987** [biscolab/laravel-authlog#1]
when I run artisan migrate, I get this error:

Cannot add foreign key constraint (SQL: alter table `authlog` add constraint `fk_authlog_blame_on_user` foreign key (`blame_on_user_id`) references `users` (`id`) on delete RESTRICT

I add primary key on user table but obtain the same error :(
need help

**Comment by nachete1987** [comment]
I resolve the issue modify the creation of id, user_id and blame_on_user id as follow
 $table->bigIncrements('id');
 $table->bigInteger('user_id')->unsigned();
 $table->bigInteger('blame_on_user_id')->unsigned()->nullable();

but when I execute php artisan vendor:publish --provider="Biscolab\LaravelAuthLog\AuthLogServiceProvider" --tags="migrations", no migration file is generated so I can not modify properly.

**Comment by biscolab** [comment]
Hi @nachete1987, default CreateUsersTable migration is `$table->increments('id');` but becomes `$table->bigIncrements('id');` since version 5.8.
I'll fix that soon.
Thanks and please next time provide more details as requested in the **issues template**

**Comment by nachete1987** [comment]
Yes, its a change that was introduced since 5.8 version
Thanks and sorry for no issue template inform.
